### ISSUE TITLE
Commands running twice on single call

### ISSUE THREAD

**Issue by mshapiro018** [ZekeSnider/Jared#26]
I am having an issue in the current release of commands running twice on a single call.

**Comment by ZekeSnider** [comment]
Could you provide some reproduction steps? What command specifically, or is it with all commands?

**Comment by mshapiro018** [comment]
I was trying to build a message bot using Jared some time ago for fun, I don’t remember exactly what happened, but I think it was receiving duplicate messages. This might have just been an issue on my end. I can try to see if the issue still exists if you are still interested.

**Comment by fernandi** [comment]
I've just installed Jared and I got this problem too.
![image](https://user-images.githubusercontent.com/12683503/72178790-ee7d4000-33e3-11ea-9e02-11879da7784f.png)
(i'm writing to myself in the screenshot)

Configuration : 
macOsMojave 10.14; Jared 1.2

**Comment by mshapiro018** [comment]
Yeah, that looks about like what I remember.

**Comment by kjb085** [comment]
@ZekeSnider Correct me if I'm wrong, but I think the issue here is that you're sending messages from the same account that Jared is running on, so Jared is picking up the command from both the sent and received message. May still be a bug, but @mshapiro018 if you try setting up a separate Apple ID to run Jared on, your issue may be resolved. That being said, I understand if that will defeat your purpose of wanting to use Jared, so that may not be the solution that you're looking for.

**Comment by ZekeSnider** [comment]
Sorry for the extremely late reply, but yes that sounds right to me. iMessage is a little weird when it comes to sending messages to yourself.
